apiVersion: v1
kind: ConfigMap
metadata:
  name: evershop-config
  namespace: resilientops
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: postgres
  DB_USER: postgres
  NODE_ENV: production
  SHOP_HOME_URL: http://localhost:3000
