apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: evershop
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Riya-te/evershop-self-healing-platform.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: resilientops

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true